included:
  - TieredGridLayout
  - TieredGridLayoutTests
  - TieredGridLayoutUITests
excluded:
  - .build
  - DerivedData

disabled_rules:
  - trailing_whitespace
  - line_length

opt_in_rules:
  - empty_count
  - force_unwrapping
  - sorted_imports
  - vertical_whitespace

analyzer_rules:
  - unused_declaration
  - unused_import

identifier_name:
  min_length: 2
  excluded:
    - id
    - x
    - y

reporter: "xcode" 