name: TieredGridLayout # プロジェクト名
options:
  bundleIdPrefix: com.akitorahayashi.TieredGridLayout
path: TieredGridLayout.xcodeproj
targets:
  TieredGridLayout:
    type: framework
    platform: iOS
    deploymentTarget: "17.0"
    sources: TieredGridLayout
    info:
      path: TieredGridLayout/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.TieredGridLayout
        GENERATE_INFOPLIST_FILE: YES

  SampleApp:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources: SampleApp
    dependencies:
      - target: TieredGridLayout
    info:
      path: SampleApp/Info.plist
      properties:
        UILaunchStoryboardName: LaunchScreen
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.TieredGridLayout.SampleApp
        GENERATE_INFOPLIST_FILE: YES
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        # DEVELOPMENT_TEAM: 