name: TieredGridLayout # プロジェクト名
options:
  bundleIdPrefix: com.akitorahayashi.TieredGridLayout
path: TieredGridLayout.xcodeproj
packages:
  TieredGridLayout:
    path: ./
targets:
  SampleApp:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources: SampleApp
    dependencies:
      - package: TieredGridLayout
    info:
      path: SampleApp/Info.plist
      properties:
        UILaunchStoryboardName: LaunchScreen
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.TieredGridLayout.SampleApp
        GENERATE_INFOPLIST_FILE: YES
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        # DEVELOPMENT_TEAM:
