name: SampleApp
options:
  bundleIdPrefix: com.akitorahayashi.TieredGridLayout.SampleApp
packages:
  TieredGridLayout:
    path: .
schemes:
  TieredGridLayoutUITests:
    path: TieredGridLayoutUITests
    build:
      targets:
        TieredGridLayoutUITests: all
    test:
      targets:
        - TieredGridLayoutUITests
      config: Debug
      gatherCoverageData: false
    run:
      config: Debug
targets:
  SampleApp:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - SampleApp
      - SampleApp/Shared
    dependencies:
      - package: TieredGridLayout
    info:
      path: SampleApp/Info.plist
      properties:
        UILaunchStoryboardName: LaunchScreen
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.TieredGridLayout.SampleApp
        GENERATE_INFOPLIST_FILE: YES
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        # DEVELOPMENT_TEAM:

  # --- UIテストターゲット ---
  TieredGridLayoutUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - TieredGridLayoutUITests
      - SampleApp/Shared/TestingConstants.swift
    dependencies:
      - target: SampleApp
      - package: TieredGridLayout
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.TieredGridLayoutUITests
        GENERATE_INFOPLIST_FILE: YES
        # DEVELOPMENT_TEAM:
        TEST_TARGET_NAME: SampleApp
