name: TieredGridLayout # プロジェクト名
options:
  bundleIdPrefix: com.akitorahayashi.TieredGridLayout
path: TieredGridLayout.xcodeproj
packages:
  TieredGridLayout:
    path: ./
targets:
  SampleApp:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources: SampleApp
    dependencies:
      - package: TieredGridLayout
    info:
      path: SampleApp/Info.plist
      properties:
        UILaunchStoryboardName: LaunchScreen
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.TieredGridLayout.SampleApp
        GENERATE_INFOPLIST_FILE: YES
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        # DEVELOPMENT_TEAM:

  # --- ユニットテストターゲット ---
  TieredGridLayoutTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "16.0"
    sources: TieredGridLayoutTests
    dependencies:
      - package: TieredGridLayout # target から package に変更
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.TieredGridLayoutTests
        GENERATE_INFOPLIST_FILE: YES
        # DEVELOPMENT_TEAM:
        TEST_HOST: # フレームワークテストのため空

  # --- UIテストターゲット ---
  TieredGridLayoutUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "16.0"
    sources: TieredGridLayoutUITests
    dependencies:
      - target: SampleApp
      - package: TieredGridLayout # target から package に変更
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.TieredGridLayoutUITests
        GENERATE_INFOPLIST_FILE: YES
        # DEVELOPMENT_TEAM:
        TEST_TARGET_NAME: SampleApp # テスト実行対象アプリ名
