name: Run Tests

on:
  workflow_call:
    outputs:
      test_result:
        description: "Test Result"
        value: ${{ jobs.build-and-test.result }}

jobs:
  build-and-test:
    runs-on: macos-latest
    env:
      MINT_PATH: ${{ github.workspace }}/.mint
    outputs:
      result: ${{ job.status }}
    steps:
    - uses: actions/checkout@v4

    - name: Cache Mint packages
      uses: actions/cache@v4
      id: cache-mint-packages
      with:
        path: ${{ env.MINT_PATH }}
        key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
        restore-keys: |
          ${{ runner.os }}-mint-

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.2'

    - name: Install Mint
      run: brew install mint
      
    - name: Generate Xcode Project
      run: mint run xcodegen generate

    - name: Create Test Output Directories
      run: mkdir -p ci-outputs/test-results/unit ci-outputs/test-results/ui ci-outputs/test-results/DerivedData
        
    - name: Make find-simulator script executable
      run: chmod +x .github/scripts/find-simulator.sh

    - name: Select Simulator
      id: select_simulator
      run: |
        SIMULATOR_ID=$(./.github/scripts/find-simulator.sh)
        echo "シミュレータ ID ($SIMULATOR_ID) が選択されました"
        echo "simulator_id=$SIMULATOR_ID" >> $GITHUB_OUTPUT

    - name: Build for Testing
      run: |
        set -o pipefail
        echo "シミュレータ ID (${{ steps.select_simulator.outputs.simulator_id }}) を使用してテスト用にビルドします"
        
        echo "Building for Unit Tests (TieredGridLayoutTests)..."
        xcodebuild build-for-testing \
          -project "TieredGridLayout.xcodeproj" \
          -scheme "TieredGridLayoutTests" \
          -destination "platform=iOS Simulator,id=${{ steps.select_simulator.outputs.simulator_id }}" \
          -derivedDataPath ./ci-outputs/test-results/DerivedData \
          -configuration Debug \
          CODE_SIGNING_ALLOWED=NO \
          | xcbeautify
          
        echo "Building for UI Tests (TieredGridLayoutUITests)..."
        xcodebuild build-for-testing \
          -project "TieredGridLayout.xcodeproj" \
          -scheme "TieredGridLayoutUITests" \
          -destination "platform=iOS Simulator,id=${{ steps.select_simulator.outputs.simulator_id }}" \
          -derivedDataPath ./ci-outputs/test-results/DerivedData \
          -configuration Debug \
          CODE_SIGNING_ALLOWED=NO \
          | xcbeautify
      continue-on-error: false
      
    - name: Run Unit Tests
      id: unit_tests
      run: |
        set -o pipefail
        echo "シミュレータ ID (${{ steps.select_simulator.outputs.simulator_id }}) を使用してユニットテストを実行します"
        xcodebuild test-without-building \
          -project "TieredGridLayout.xcodeproj" \
          -scheme "TieredGridLayoutTests" \
          -destination "platform=iOS Simulator,id=${{ steps.select_simulator.outputs.simulator_id }}" \
          -derivedDataPath ./ci-outputs/test-results/DerivedData \
          -enableCodeCoverage NO \
          -resultBundlePath ./ci-outputs/test-results/unit/TestResults.xcresult \
          | xcbeautify --report junit --report-path ./ci-outputs/test-results/unit/junit.xml
        
        XCODEBUILD_EXIT_CODE=${PIPESTATUS[0]}
        echo "UNIT_TEST_XCODEBUILD_STATUS=$XCODEBUILD_EXIT_CODE" >> $GITHUB_ENV
        ls -la ./ci-outputs/test-results/unit/
      continue-on-error: false
      
    - name: Verify Unit Test Results
      run: |
        echo "Checking for Unit Test results bundle..."
        RESULT_BUNDLE_PATH="./ci-outputs/test-results/unit/TestResults.xcresult"
        if [ ! -d "$RESULT_BUNDLE_PATH" ]; then
          echo "❌ Error: Unit test result bundle not found at $RESULT_BUNDLE_PATH"
          exit 1
        fi
        echo "✅ Unit test result bundle found at $RESULT_BUNDLE_PATH"
      continue-on-error: false

    - name: Run UI Tests
      id: ui_tests
      run: |
        set -o pipefail
        echo "シミュレータ ID (${{ steps.select_simulator.outputs.simulator_id }}) を使用して UI テストを実行します"
        xcodebuild test-without-building \
          -project "TieredGridLayout.xcodeproj" \
          -scheme "TieredGridLayoutUITests" \
          -destination "platform=iOS Simulator,id=${{ steps.select_simulator.outputs.simulator_id }}" \
          -derivedDataPath ./ci-outputs/test-results/DerivedData \
          -enableCodeCoverage NO \
          -resultBundlePath ./ci-outputs/test-results/ui/TestResults.xcresult \
          | xcbeautify --report junit --report-path ./ci-outputs/test-results/ui/junit.xml
          
        XCODEBUILD_EXIT_CODE=${PIPESTATUS[0]}
        echo "UI_TEST_XCODEBUILD_STATUS=$XCODEBUILD_EXIT_CODE" >> $GITHUB_ENV
        ls -la ./ci-outputs/test-results/ui/
      continue-on-error: false

    - name: Verify UI Test Results
      run: |
        echo "Checking for UI Test results bundle..."
        RESULT_BUNDLE_PATH="./ci-outputs/test-results/ui/TestResults.xcresult"
        if [ ! -d "$RESULT_BUNDLE_PATH" ]; then
          echo "❌ Error: UI test result bundle not found at $RESULT_BUNDLE_PATH"
          exit 1
        fi
        echo "✅ UI test result bundle found at $RESULT_BUNDLE_PATH"
      continue-on-error: false

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: ci-outputs/test-results
        retention-days: 7 