name: Swift Package Tests 

on:
  workflow_call:
    outputs:
      package_test_result:
        description: "Swift Package Test Result" 
        value: ${{ jobs.test-package.outputs.result }}

jobs:
  test-package:
    runs-on: macos-latest
    outputs:
      result: ${{ steps.run_tests.outcome }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Xcode 
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - name: Build Swift Package
        id: build_package
        run: |
          echo "Swift Packageをビルド中..."
          swift build
        continue-on-error: false

      - name: Test Swift Package 
        id: run_tests
        if: steps.build_package.outcome == 'success'
        run: |
          echo "Swift Packageをテスト中..."
          swift test
        continue-on-error: true

      - name: Check Test Step Outcome 
        if: always() && steps.build_package.outcome == 'success' && steps.run_tests.outcome != 'success'
        run: |
          echo "Swift Package のテストが失敗しました。"
          # exit 1
          
      - name: Check Build Step Outcome 
        if: steps.build_package.outcome != 'success'
        run: |
          echo "Swift Package のビルドが失敗しました。"
          # exit 1