name: Tiered Grid Layout CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-format:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Mint
        run: |
          brew install mint
          
      - name: Install dependencies via Mint
        run: |
          mint bootstrap
          
      - name: Format Swift files
        run: |
          mint run swiftformat .
          
      - name: SwiftLint Autocorrect
        run: |
          mint run swiftlint autocorrect
          
      - name: Run SwiftLint
        run: |
          mint run swiftlint lint --strict
          
      - name: Check for changes after formatting
        run: |
          git diff --exit-code || { echo "Code formatting issues found. Please run SwiftFormat and SwiftLint locally and commit changes."; exit 1; }
          
  build-and-ui-test:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set Xcode version
        run: sudo xcode-select -s /Applications/Xcode.app
          
      - name: Build
        run: |
          xcodebuild build -project TieredGridLayout.xcodeproj -scheme TieredGridLayout -destination "platform=iOS Simulator,name=iPhone 15" | xcpretty
          
      - name: Run UI tests
        run: |
          xcodebuild test -project TieredGridLayout.xcodeproj -scheme TieredGridLayoutUITests -destination "platform=iOS Simulator,name=iPhone 15" | xcpretty 