name: Tiered Grid Layout CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  copilot-review:
    name: Copilot Review
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    permissions:
      contents: read
      pull-requests: write
      
    steps:
      - uses: actions/checkout@v3
      
      - name: Add PR Review Comment (Simulated)
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.payload.pull_request.number,
              body: "👋 Copilotレビュー: コード全体をチェックします"
            });

  check-and-build:
    name: Check and Build
    runs-on: macos-latest
    # このジョブは常に実行される (依存関係なし)

    steps:
      # --- セットアップ ---
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Mint
        run: |
          brew install mint
          
      - name: Install dependencies via Mint
        run: |
          mint bootstrap

      # --- Lint & Format ---
      - name: Show Tool Versions
        run: |
          mint run swiftlint version
          mint run swiftformat --version
          
      - name: Format Swift files
        run: |
          mint run swiftformat .
      
      - name: Run SwiftLint
        run: |
          mint run swiftlint lint --strict
          
      - name: Check for changes after linting (should be none)
        run: |
          git diff --exit-code || { echo "コードフォーマットの問題が見つかりました。ローカルで SwiftFormat と SwiftLint を実行し、変更をコミットしてください。"; exit 1; }
            
      # --- Build ---
      - name: Set Xcode version
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Generate Xcode project
        run: |
          mint run xcodegen generate

      - name: Build Sample App
        run: |
          xcodebuild build -project TieredGridLayout.xcodeproj -scheme SampleApp -destination "platform=iOS Simulator,name=iPhone 15" | xcpretty